#provider: cassandra, postgres, mongo
provider:
  name: postgresql
  options:
    dynamic_schema: "no"

#strict, compatibility
mode: "strict"
#mutations, audit, all
generate: "all"

source: "./database/postgres"

#stdout if path is not provided
output: "output"
