#provider: cassandra, postgres, mongo
provider:
  name: postgres
  options:
    dynamic_schema: "no"
    ext: ".sql.j2"

#strict, compatibility
mode: "strict"
#mutations, audit, all
generate: "all"

source: "./database/postgres"


output:
  #stdout if path is not provided
  path: "output"
  pad: "4"
  prefix: "V"

