name: KotlinCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build Gradle
        run: ./gradlew clean build

      - run: "echo print vars"
      - name: Echo Env
        shell: bash
        run: |
          echo "docker username ${{ secrets.DOCKER_HUB_USER }}"
      - run: "echo print complete"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: typeboot/typeboot-spec:__GIT_TAG__

